### ISSUE TITLE
Able to use http instead of https for callback URI ?

### ISSUE THREAD

**Issue by greglever** [AngellusMortis/django_microsoft_auth#126]
Hi,

Using `OAuth2Session` from `requests_oauthlib` one can specify a redirect URI to have http as well as https and I've got this to work with my current AD setup. I've seen in the README that it says that https must be used, but I was wondering if it's possible to configure http to be used ?

Thanks, 

Greg

**Comment by AngellusMortis** [comment]
No. The HTTPS requirement comes from Microsoft.
