### ISSUE TITLE
Two users found during authentication, then exception

### ISSUE THREAD

**Issue by colegatron** [AngellusMortis/django_microsoft_auth#132]
* Django Microsoft Authentication Backend version:  django-microsoft-auth==1.1.1
* Django: Django==2.0.5
* Python version: Python 3.6.7
* Operating System: AWS AMI Linux; Docker container: FROM python:3.6

### Description

Trying to login with my email authenticating against Office365
Other domain users worked properly; first login fails, then I give them rights and then everything works
When I tried to login with my email account I got an error

### What I Did

When I type my email address I am asked to choose between my personal account and work account (both share the same email address, different passwords, different Microsoft user backend database).

I choose work account.
After type the password I got an Exception: 

> MultipleObjectsReturned at /microsoft/auth-callback/
> get() returned more than one User -- it returned 2!
> Request Method: | POST
> Request URL: http://domain.com/microsoft/auth-callback/
> Django Version: 2.0.5
> Exception Type: MultipleObjectsReturned
> Exception Value: get() returned more than one User -- it returned 2!
> Exception Location: /usr/local/lib/python3.6/site-packages/django/db/models/query.py in get, line 407
> Python Executable: /usr/local/bin/python
> Python Version: 3.6.7
> Python Path: ['/app',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/site-packages']
> Server time: Fri, 9 Nov 2018 12:40:25 +0000

Do not know how to proceed

**Comment by AngellusMortis** [comment]
This would definitely be a bug. It looks like you signed up with both your personal and work accounts and it is returning both of them (which `.get` is only expecting one so it throws an error). 

As a workaround, you can either log in as another admin user and delete one of the accounts, or you can use the Django shell (`manage.py shell`) to delete one of the user accounts. As an alternative to deleting, you should be able to change the email on one of them.

**Comment by colegatron** [comment]
The fact is the user has not been created in the django db. The error happens right after the auth phase and before returning to the application from the auth-module.

Since I am asked, in the office365 popup, which user account (personal/work) I want to use when authenticating, I am curious why the heck it returns two users instead of the one I selected.

**Comment by AngellusMortis** [comment]
> Exception Location: /usr/local/lib/python3.6/site-packages/django/db/models/query.py in get, line 407

This is coming from the database though. 

I have not tested this with Office 365, only Microsoft Accounts and Azure AD, but I also get the prompt for multiple users and this does not give me an issue if I pick either of them. As a result, I am not 100% how you are trigger the error, but it definitely looks somehow you got two users in the database with the same email address. The only place in the `auth-callback` view that calls a `.get` on the `User` model is in the [main authentication callback](https://github.com/AngellusMortis/django_microsoft_auth/blob/master/microsoft_auth/backends.py#L146) where it is doing a lookup on the users email address.

**Comment by colegatron** [comment]
Ey, there was an user in the django db sharing same account. After rename its email address, worked flawlessly.
Thank you for notice it. I just thought it was because my double-account-same-email situation on Microsoft
