### ISSUE TITLE
Allow use of multiple sites via `self.request`

### ISSUE THREAD

**Issue by 2ps** [AngellusMortis/django_microsoft_auth#187]
* Django Microsoft Authentication Backend version: 1.3.0
* Python version: 3.6.7
* Operating System: ubuntu 18.05

### Description

We have a site with multiple URLs (e.g., one for private-facing, one for public-facing).  we should be able to login using all of the urls).  This can be fixed by passing `self.request` into the call to `Site.objects.get_current` which will allow us to configure multiple sites rather than allowing us to specify only one `SITE_ID`.

**Comment by AngellusMortis** [comment]
See my comments on your PR: https://github.com/AngellusMortis/django_microsoft_auth/pull/188#issuecomment-470367762

Once you adjust the code and add the new tests, feel free to reopen the PR.

**Comment by AngellusMortis** [comment]
This has been completed on the `master`. I will cut a new release shortly as there is one more feature I would like to add first.
