### ISSUE TITLE
Using django_microsoft_auth with Django Rest Framework

### ISSUE THREAD

**Issue by raflopjr** [AngellusMortis/django_microsoft_auth#195]
Django Microsoft Authentication Backend version: 1.3.0
Python version: 3.7
Django Version: 2.1.7
Operating System: Windows 10 Enterprise
Google Chrome Version 72.0.3626.121
Chrome Extensions:

Ublock Origin
Laspass
Todoist

### Description

Has anyone successfully used this library with Django Rest Framework yet? I am looking to implement it, and can write documentation for the docs once I do it. I was curious if anyone had done so already or had any suggestions. Also, are issues the appropriate way to ask this?

**Comment by AngellusMortis** [comment]
There should be no issues integrating this with DRF. You can make seralizers for any of the provided models if you want and expose them via DRF endpoints just fine. All of that work would be out of the scope of this module though, including the documentation on how to do so. I would recommend checking out the [DRF docs](https://www.django-rest-framework.org) for that.

If you are talking about making a authentication class that will work, you do not need to. `microsoft_auth` is 100% built on top of Django's existing user authentication system and you obviously should not use Microsoft provided JWT id_tokens to authenticate against your app. They will expire unless you request the `offline_access` scope, which you should not. You should make your own DRF compatible authentication system that uses Django authentication, not Microsoft's so you are not refreshing your tokens from a third party. If you want to integrate your own OAuth system into DRF, check out [their authentication docs](https://www.django-rest-framework.org/api-guide/authentication/#third-party-packages).

If you need to login user and get into your database, you will need to make a view on your frontend that redirects the user to Microsoft's authorize view (see `microsoft_auth/templates/microsoft/admin_login.html` for examples of how I am doing that for the Admin login).

If you would like to add more documentation on how to implement your own login view, please feel free to add docs based on what you did. I will never turn down related documentation PRs.

**Comment by raflopjr** [comment]
What I'm really after is your last suggestion. I want to implement a login to access the database via microsoft and then let Django DRF access. 

The part I'm a little lost on is getting the login url that the pop up uses, and how I pipe the response from that through my front end (Vue.js) and back to django to authenticate.

**Comment by AngellusMortis** [comment]
See https://github.com/AngellusMortis/django_microsoft_auth/blob/master/microsoft_auth/templates/microsoft/admin_login.html, https://github.com/AngellusMortis/django_microsoft_auth/blob/master/microsoft_auth/static/microsoft/js/admin_login.js, and https://github.com/AngellusMortis/django_microsoft_auth/blob/master/microsoft_auth/templates/microsoft/auth_callback.html

Basically I have a `context_processor` that exposes the authorization URL to the Javascript (you can do the same with a DRF API endpoint that just redirects you to the authorization URL. This authorization URL is opened in a new tab and then when you log into Microsoft, it redirects you back to the `auth_callback` view, which then passes a message back up to the window that opened it with the details on the authentication attempt and closes itself.

**Comment by raflopjr** [comment]
Hello, I hit another wall but I think I am close. I've set up an endpoint from Django Rest Framework which returns the authorization URL. This is used by Vue JS to open a window and auth, but when it's done authenticating, I get the following error:
```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:8000') does not match the recipient window's origin ('http://localhost:8080').
```

This makes sense to me since Vue and Django will be coming from two separate domains. How is it that i can take the contents that the login returns, and ultimately get a session token from DRF that Vue can store and use to populate views?

**Comment by AngellusMortis** [comment]
Checkout version 2.2.0, `MICROSOFT_AUTH_CALLBACK_HOOK` in `microsoft_auth.conf`.

https://github.com/AngellusMortis/django_microsoft_auth/blob/master/microsoft_auth/conf.py#L137

I added a hook right before `auth-callback` returns a response so you can override the origin for `postMessage` as well inject any extra data you want to be passed back up as well (like if you need to issue an access token for DRF for Vue.js to use)

**Comment by raflopjr** [comment]
From the docstring it seems that it's exactly what I need. I am not familiar with the syntax of the hook. It appears it takes a string, a docstring and type, is this correct? For my custom code should the empty string be replaced with a function call?

**Comment by raflopjr** [comment]
I read through your code and I think I have a better understanding of the hooks. It seems that the dictionary in `conf.py` is used for values not specified in `settings.py`. I followed the logic up to the `get_hook` function in `utils.py` which grabs the value of `MICROSOFT_AUTH_CALLBACK_HOOK` and splits on the last period. This results in a value requirement of a string that is alike to the dot notation used for any other python import with the function name as the last entry after the last period.

I may have missed something but it seems like the hook can only use packages and modules installed or possibly relative imports from the cwd which I am uncertain for Django but I would assume it in the same directory as `manage.py`.

**Comment by raflopjr** [comment]
Follow Up!

This seems to work exactly like my previous post. MAKE SURE YOU'RE on 2.2.0 and above. I installed around two weeks ago so I had missed those changes. But after updating the updated settings.py file worked great. Now I have access to the hook and will try to figure out how to get proper state to auth.

**Comment by raflopjr** [comment]
I have the following code which exposes the link to my front end, opens the windows, and goes through and even updates the context and no longer gives me the post, but I am unsure as to what the next step is. In the snippet below, auth_callback is the function used with the MICROSOFT_AUTH_CALLBACK_HOOK.

```
@api_view(["GET", "POST"])
def login(request):
    login_type = ugettext_lazy("Microsoft")

    # initialize Microsoft client using CSRF token as state variable
    signer = TimestampSigner()
    state = signer.sign(get_token(request))
    microsoft = MicrosoftClient(state=state, request=request)
    auth_url = microsoft.authorization_url()[0]

    return Response(
        data={
            "microsoft_login_enabled": config.MICROSOFT_AUTH_LOGIN_ENABLED,
            "microsoft_authorization_url": mark_safe(auth_url),
            "microsoft_login_type_text": login_type,
            },
        status=status.HTTP_200_OK
        )


def auth_callback(request, context):
    context["base_url"] = "http://localhost:8080/"
    print(context)
    return context
```

**Comment by amaljithkuttamath** [comment]
Hello @raflopjr,

I am curious, if you managed to have a working sample, using this library in DRF?
Good day.
