### ISSUE TITLE
Scope has changed from "email openid" to "profile email openid".

### ISSUE THREAD

**Issue by senseialex** [AngellusMortis/django_microsoft_auth#196]
* Django Microsoft Authentication Backend version:Django Version: 2.1.7
* Python version: 3.6.8
* Operating System:LINUX
* Browser and version you are testing in:Chrome
* What browser plugins do you have installed that may interfere with cookies or Javascript:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did
 I get this error when I try to login
Scope has changed from "email openid" to "profile email openid".
Can I do something?

**Comment by AngellusMortis** [comment]
Ugh. I wish Microsoft would make up their mind. I tried to remove `profile` so I was not requesting more information then I needed by default. 

Updated to 2.1.1 to fix (might take a few minutes to show up).

**Comment by senseialex** [comment]
Thanks @AngellusMortis
