### ISSUE TITLE
Application is not configured as a multi-tenant application

### ISSUE THREAD

**Issue by spuetz** [AngellusMortis/django_microsoft_auth#215]
* Django Microsoft Authentication Backend version: 2.2.1
* Python version: 3.6.7
* Operating System: Ubuntu 18.04
* Browser and version you are testing in: Mozilla Firefox 66.0.3
* What browser plugins do you have installed that may interfere with cookies or Javascript: -

### Description

I got the following message from the Microsoft Server: https://login.microsoftonline.com/common/oauth2/v2.0/authorize...
> Sign in
> 
> Sorry, but we’re having trouble with signing you in.
> AADSTS50194: Application '***' is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.

Is this a know issue?

**Comment by spuetz** [comment]
Fixed that after choosing the right `Supported account types` in the Azure Authentication Configuration Panel. It must be the general one.

**Comment by Bubbassauro** [comment]
It didn't make sense for us to change the Supported account types since ours is an internal application, so I fixed it by specifying our application tenant id. That defaults to "common" if not specified, which causes that error for newer applications.

Added to settings.py:
`MICROSOFT_AUTH_TENANT_ID='*******-****-****-************'`

**Comment by Perzan** [comment]
> 
> 
> It didn't make sense for us to change the Supported account types since ours is an internal application, so I fixed it by specifying our application tenant id. That defaults to "common" if not specified, which causes that error for newer applications.
> 
> Added to settings.py:
> `MICROSOFT_AUTH_TENANT_ID='*******-****-****-************'`

This worked, but is there a way to change the redirect URI? My app (on Azure) is configured to redirect to `http://localhost:5000`, but the app (in Django) keeps trying to go to `example.com` (The URL to the Microsoft login has the following query parameter: `redirect_uri=http%3A%2F%2Fexample.com%2Fmicrosoft%2Fauth-callback%2F`).
