### ISSUE TITLE
TypeError at /microsoft/auth-callback/ Expecting a PEM- or RSA-formatted key.

### ISSUE THREAD

**Issue by senseialex** [AngellusMortis/django_microsoft_auth#219]
* Django Microsoft Authentication Backend version:2.2.2
* Python version: 3.7
* Operating System: Windows
* Browser and version you are testing in: chrome
* What browser plugins do you have installed that may interfere with cookies or Javascript:

### Description

I receive this error 
Internal Server Error: /microsoft/auth-callback/
TypeError at /microsoft/auth-callback/ Expecting a PEM- or RSA-formatted key.

### What I Did
Access on admin site

**Comment by AngellusMortis** [comment]
Not enough information to reproduce. I need more information on the specific steps you took to set up the library.
