### ISSUE TITLE
What is the proper way of passing claims on authorization?

### ISSUE THREAD

**Issue by marteinn** [AngellusMortis/django_microsoft_auth#221]
First of, thanks for a great library!

I have a question, I want to run custom code based on user claims on user authorization, right now the only way I see it (without extending / modifying the library).

- Create the hook "MICROSOFT_AUTH_AUTHENTICATE_HOOK"
- Retrieve the token in that hook
- Generate a public_key
- Retrieve claims by combining token/public key and run  a decode

Am I missing something, is there a easier way? 

Currently I have experimented with building my own backend that extends upon MicrosoftAuthenticationBackend, which in the end makes sure the hook gets the claims. But I would love to have a easier solution :)

Thanks!
/Martin

**Comment by AngellusMortis** [comment]
>  custom code based on user claims on user authorization

That is the [point of MICROSOFT_AUTH_AUTHENTICATE_HOOK](https://github.com/AngellusMortis/django_microsoft_auth/blob/master/microsoft_auth/backends.py#L202). It is password the raw [OAuth2Token object](https://github.com/oauthlib/oauthlib/blob/master/oauthlib/oauth2/rfc6749/tokens.py#L28).

If you need to retrieve the claims form it, the `MicrosoftClient` can already do that for you via the [get_claims method](https://github.com/AngellusMortis/django_microsoft_auth/blob/master/microsoft_auth/client.py#L95). It already validates the token from the OIDC configuration URL for the tenant you are using and everything. 

Something like this should work:

```python
from microsoft_auth.client import MicrosoftClient

def authenticate_hook(user, token)
     client = MicrosoftClient()
     client.token = token
     client.get_claims()
```

**Comment by marteinn** [comment]
Works brilliantly, thanks @AngellusMortis! Perhaps this would fit nicely on a FAQ / common patterns documentation page?
