### ISSUE TITLE
Related to #141 - "Bad State"

### ISSUE THREAD

**Issue by AliNjie** [AngellusMortis/django_microsoft_auth#230]
#### Django Microsoft Authentication Backend version:
2.2.2
#### Django version:
2.2.1
#### Python version:
3.7.2
#### Operating System:
Windows 10 1809
#### Browser and version:
Google Chrome - 74.0.3729.169
#### Browser extensions/plugins you have installed:
Not related, but:
- LastPass
- React
- Redux
- JSON formatter

### Description
I'm trying to authenticate via Azure AD with my Microsoft account. The authentication seems to be successful as I receive an authorization code, but the callback is where the error happens.

What I'm trying to achieve is to require all requests to be authenticated. I've made a custom middleware that does the following redirects the user to the authentication URL if `request.users.is_authenticated` equals False.
*Note*: I am able to log in with my account in the /admin site.

#### My custom middleware
```python
from django.middleware.csrf import get_token
from django.shortcuts import redirect

def require_auth(get_response):
    # One-time configuration and initialization.

    def middleware(request):
        # Code to be executed for each request before
        # the view (and later middleware) are called.

        if not request.user.is_authenticated:
            if request.path != '/microsoft/auth-callback/':
                state = get_token(request)
                return redirect(
                    f'https://login.microsoftonline.com/<My-tenant-id>/oauth2/v2.0/authorize?response_type=code&client_id=<My-Client-ID>&response_mode=form_post&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fmicrosoft%2Fauth-callback%2F&scope=openid+email+profile&state={state}'
                )

        response = get_response(request)

        # Code to be executed for each request/response after
        # the view is called.

        return response

    return middleware
```

The request:
URL: `Request URL: http://localhost:8080/microsoft/auth-callback/`
Method: `POST`
Status Code: `400` (Bad Request)
Form Data:
- Code: My authorization code
- State: CSRF value
- Session State: GUID

The response/error
```
This window should automatically close. If it does not, it should be save to close after a few seconds.

{"microsoft_auth": {"error": "bad_state", "error_description": "An invalid state variable was provided. Please refresh the page and try again later."}}
```

### Environment Setup Steps
My environment is set up according to the [documentation]("https://django-microsoft-auth.readthedocs.io/en/latest/"). 

### Steps to Reproduce
1. Set up Django Microsoft Authentication as described in the docs.
2. Implement middleware.
3. Navigate to any site (And you will be redirected to Microsoft's login page)
4. Log in with your credentials.
5. Error message

**Comment by AngellusMortis** [comment]
You are generating your state improperly.

It also needs to be signed by the application.

See
https://github.com/AngellusMortis/django_microsoft_auth/blob/master/microsoft_auth/context_processors.py#L46

https://github.com/AngellusMortis/django_microsoft_auth/blob/master/microsoft_auth/views.py#L95

**Comment by AliNjie** [comment]
Worked like a charm! Thanks a lot for your quick response 👍

**Comment by mateoopa** [comment]
@AngellusMortis I'm getting the same error, I'm struggling with this issue since 2 days ago. I haven't been able to fix it
