### ISSUE TITLE
Redirect to another page (not admin) and logout

### ISSUE THREAD

**Issue by oscar-rolando-alvarez** [AngellusMortis/django_microsoft_auth#239]
Django Microsoft Authentication Backend version: 2.2.3

    Django version: 2.2.1

    Python version: 3.6.8

    Operating System: Ubuntu 18.04

**Description**
Hi.

I'm trying to create an app using django_microsoft_auth as backend for login and logout, however I could not redirect to another page (not admin) like dashboard or index. And here is another question. How is the procedure for logout?

Could you help me with those things?

Best regards.

Oscar Alvarez

**Comment by AngellusMortis** [comment]
The login page provided out of the box is only for the Admin Site. If you want a log in page that functions for other parts of the site, you [need to make your own](https://docs.djangoproject.com/en/2.2/topics/auth/default/#authentication-in-web-requests).

You can see my [Admin Login template](https://github.com/AngellusMortis/django_microsoft_auth/blob/master/microsoft_auth/templates/microsoft/admin_login.html) and the [Django Admin login view](https://github.com/django/django/blob/master/django/contrib/admin/sites.py#L376) combined with the Django docs above for how make your own login view.
