### ISSUE TITLE
Login only working in private mode of browser (for Firefox & Chrome)

### ISSUE THREAD

**Issue by kummerer94** [AngellusMortis/django_microsoft_auth#243]
Hey there! Great project and great execution! I was especially happy when I found out there you are validating the ID token you get back from Microsoft.

Still, I encountered one nasty bug when I tried to use the tool.

* Django Microsoft Authentication Backend version: 2.3.0
* Django version: 2.1.9
* Python version: 3.7.1
* Operating System: Windows 10 (Version 1903)
* Browser and version: Firefox Developer Edition 68.0b10
* Browser extensions/plugins you have installed: Kee, React Tools, Vue Tools, Firefox Container

### Environment Setup Steps

I followed your tutorial on how to setup the things in the backend. My issue is not related to the backend, however. I run a vanilla Django 2.1.9 and configured the site etc. according to your guide.

### Steps to Reproduce

Login in Firefox (+ Chrome) does not work. I tried logging into the application's backend. When I am in private mode (Firefox or Chrome) the login does work. 

1. Go to the `/admin` site.
2. Click on "Microsoft".
3. Popup Window opens. I login there.
4. Popup Window closes. Nothing happens. (Reloading shows that I am not logged in.)

This made me investigate the frontend a little bit more. I found out that the following event listener does not catch the corresponding event (line 13 in `login.js`):

```javascript
window.addEventListener('message', this.receiveMessage.bind(this));
```

When I am trying to login, this event is not fired when the window is closed. However, when I am running in private mode, it is fired. I already tried googling if this has something to do with the MessageEvent itself or if there is a know bug but I was not able to find anything.

(Also: Is this related #192?)

Thanks for the help!

Alex

**Comment by kummerer94** [comment]
Okay. I found the bug myself.

Just make sure that when you are using Django locally that you either use localhost or 127.0.0.1 to visit the site. If you mix both, you will eventually not be able to send a message through the postMessage API because the hosts do not match. I found out by debugging the little popup browser window.

Closing this!

**Comment by AngellusMortis** [comment]
I was about to reply saying I could not reproduce the issue. Haha. Also, make sure you do not use `127.0.0.1`, always use `localhost` for local testing. Microsoft only allows `http` over `localhost`. 

![image](https://user-images.githubusercontent.com/490848/59682773-e5592700-91a4-11e9-9c59-34587bf0210e.png)
