### ISSUE TITLE
The exception thrown for sqlite3 db is different than one thrown for mysql

### ISSUE THREAD

**Issue by tlam** [AngellusMortis/django_microsoft_auth#253]
* Django Microsoft Authentication Backend version: 2.3.0
* Django version: 2.2.3
* Python version: 3.7.2
* Operating System: macOS 10.14.5

### Description

After following the description at https://django-microsoft-auth.readthedocs.io/en/latest/usage.html to setup the library, running `python manage.py migrate` gives me the error:

    django.db.utils.ProgrammingError: (1146, "Table 'mydatabase.django_site' doesn't exist")
In this project configuration, I am using MySQL instead of the default sqlite3.

### Steps to Reproduce

- Create a brand new django2 project
- Set the DATABASE to MySQL
- Follow the setup steps at https://django-microsoft-auth.readthedocs.io/en/latest/usage.html
- After running `python manage.py migrate`, you will get `Table django_site` doesn't exist

### Possible Solution

At https://github.com/AngellusMortis/django_microsoft_auth/blob/master/microsoft_auth/apps.py#L41, it's catching `OperationalError`. Django configured with MySQL returns the exception `django.db.utils.ProgrammingError`. It might best to also catch it there:

    from django.db.utils import ProgrammingError

    except (OperationalError, ProgrammingError):

**Comment by AngellusMortis** [comment]
Fixed in 2.3.1. Thanks @theilgaard
