### ISSUE TITLE
Heroku Deploy

### ISSUE THREAD

**Issue by mgsaltman** [AngellusMortis/django_microsoft_auth#286]
Hi There,

I’ve trying to get my website up and running for the last couple days and can’t see to figure out what’s going on. 

When I run the app locally and go to the admin page I see a button for Windows and Password as expected. When I click on Windows I get a popup saying the redirect_uri doesn’t match which is also expected since it’s http vs https. 

When I deploy onto Heroku the app loads fine and so does the admin page but when I click the Windows button nothing happens and I don’t think it’s becuase a popup is being blocked. 

Do I need to make a sign in page and if so what’s the best way to do that? All I need is authentication so that I can build a company intranet but really struggling. 

Any help is greatly appreciated!

**Comment by davidppf** [comment]
Hi,

I am getting this error:
