### ISSUE TITLE
Login with Microsoft Office365 is getting failed. 

### ISSUE THREAD

**Issue by IOException722** [AngellusMortis/django_microsoft_auth#31]
* Django Microsoft Authentication Backend version:
* Python version: 3.5
* Operating System: Ubuntu 16.04

### Description

Login with Microsoft Office365 is getting failed.  It din't created user in django admin unlike its mentioned in tutorial as it should create. I can only see two accounts(Microsoft accounts and Microsoft xbox-live accounts but not Microsoft office 365 accounts)

**Comment by AngellusMortis** [comment]
Sorry, I never got a notification for this. 

The only actual difference between "Microsoft Accounts" and "Office 365" accounts is which authorization URL is used for the OAuth2 sign in flow. You user will be under Microsoft Accounts. 

"Microsoft Accounts" uses the older https://login.microsoftonline.com/common/oauth2/v2.0/authorize which **only** works for Microsoft Accounts. 

"Office 365" uses https://login.microsoftonline.com/common/oauth2/v2.0/authorize which will work for both Microsoft Account and Enterprise Office 365 accounts. Enterprise Office 365 accounts are ones created by orgs that are **not** actually Microsoft Accounts. For example, my university uses Office 365 accounts now. You have an Outlook email address and all of the signs of a Microsoft account, but you do not actually have one (no Xbox Live for example, I believe). 

"Xbox Live" uses the same authorization URL as the Microsoft Account flow, but it has extra steps for Xbox Live after OAuth2 flow.
