### ISSUE TITLE
Running server

### ISSUE THREAD

**Issue by anandtest58** [AngellusMortis/django_microsoft_auth#330]
I am using following command run server.
python -m tests.site runserver 0:8001

But I am getting an error as follows.
ModuleNotFoundError: No module named 'tests'

**Comment by austinjhunt** [comment]
I am getting this error as well.

**Comment by austinjhunt** [comment]
Fixed by running 'pip install tests' but then it says 'no module named tests.site'

**Comment by AngellusMortis** [comment]
`export PYTHON_PATH=/path/to/django_microsoft_auth`

**Comment by austinjhunt** [comment]
> It is because it is not searching your local path for that module.
> 
> ```
> export PYTHON_PATH=/path/to/django_microsoft_auth
> ```
> 
> https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH

Thank you for the quick fix! Setting PYTHONPATH resolved immediately.
