### ISSUE TITLE
Inability to use a single tenant app registration.

### ISSUE THREAD

**Issue by stfloyd** [AngellusMortis/django_microsoft_auth#388]
Has anyone worked around this?

* Django Microsoft Authentication Backend version: 2.3.1

* Django version: 3.0
* Python version: 3.6
* Operating System: CentOS, Windows 10
* Browser and version: Brave, Chrome, Firefox -- all latest.
* Browser extensions/plugins installed: N/A

### Description
When using the keys for an app registration that is only permissable for a single tenant the callbacks don't work and it won't authenticate. It will raise an error because the endpoint for a multi-tenant app registration is different than the single tenant flavor.

### Environment Setup Steps
Create blank django with this package and django admin.
Add keys for single tenant Azure app registration.
Try to login, get DEBUG 500 server error due to improper callback response due to incorrect url.

**Comment by tonybaloney** [comment]
You need to add the `MICROSOFT_AUTH_TENANT_ID` with the tenant ID in the Azure UI in settings.py otherwise it will use a common endpoint (which wont work for single scope)

**Comment by intelef** [comment]
> You need to add the `MICROSOFT_AUTH_TENANT_ID` with the tenant ID in the Azure UI in settings.py otherwise it will use a common endpoint (which wont work for single scope)

Thanks, Tony, solved my issue immediately. This issue could probably be closed with documentation of that settings.py configurable.
