### ISSUE TITLE
the package on pypi doesn't include the templates or static media

### ISSUE THREAD

**Issue by tubaman** [AngellusMortis/django_microsoft_auth#39]
* Django Microsoft Authentication Backend version: 1.0.4
* Python version: 3.5.3
* Operating System: Debian Stretch

### Description
After running: `pip install django_microsoft_auth`, I followed the README.  When I got to the admin loging step, I got an Django error page saying that microsoft/admin_login.html wasn't found.  When I went fishing thought my site-packages I confirmed that it wasn't there.  Also the static files(js, etc) aren't there.

When I pip installed from github: `pip install -e git+https://github.com/AngellusMortis/django_microsoft_auth.git#egg=microsoft_auth`, all works fine.  I suggest including templates and static media in the pypi package just like Django itself does.

**Comment by AngellusMortis** [comment]
I just noticed this as well. Opps. I am uploading a new version in a few minutes.
