### ISSUE TITLE
REDIRECT_URI going to example.com

### ISSUE THREAD

**Issue by chenbr** [AngellusMortis/django_microsoft_auth#407]
Versions:
Django                            3.0.6
django-microsoft-auth             2.3.1

the redirect uri that comes in the page source has "&redirect_uri=http%3A%2F%2Fexample.com%2Fmicrosoft%2Fauth-callback%2F&scope=openid+email+profile&state....."

my settings.py has all the usual suspects:

MICROSOFT_AUTH_CLIENT_ID = <redacted>
MICROSOFT_AUTH_CLIENT_SECRET = <redacted>
MICROSOFT_AUTH_TENANT_ID = <redacted>

But grepping through the codebase I dont see any environment variables that it looks for the redirect uri. I only see it in the test_client.py where its explicitly set. Am i missing something?

STDOUT When started up:
Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
?: (microsoft_auth.W002) `example.com` is still a valid site, Microsoft auth might not work
        HINT: Microsoft/Xbox auth uses OAuth, which requires a real redirect URI to come back to

System check identified 1 issue (0 silenced).
May 14, 2020 - 12:15:03
Django version 3.0.6, using settings 'mysite.settings'
Starting development server at http://0.0.0.0:13000/
Quit the server with CONTROL-C.

**Comment by Robgogo** [comment]
Same issue here. any solutions?

**Comment by chenbr** [comment]
Much like the MICROSOFT_AUTH_CLIENT_ID variable, i need a say MICROSOFT_AUTH_REDIRECT_URI variable to set this.. that would solve this.. unless again im missing something obvious.. which me grepping through the codebase doesnt seem like it..

**Comment by AngellusMortis** [comment]
You did not configured the sites framework. Read the docs.
