### ISSUE TITLE
get_claims() complaining now. 

### ISSUE THREAD

**Issue by chenbr** [AngellusMortis/django_microsoft_auth#410]
Now that https://github.com/AngellusMortis/django_microsoft_auth/pull/350 fixes my issue with the jwk, I'm getting this get_claims() got an unexpected keyword argument 'allow_refesh' error when being passed the same jwt.. Am i missing something now?

**Comment by chenbr** [comment]
its a typeerror..
Exception Type: TypeError at /microsoft/auth-callback/
Exception Value: get_claims() got an unexpected keyword argument 'allow_refesh'

**Comment by chenbr** [comment]
Any thoughts?

**Comment by chenbr** [comment]
i figured it out.. line 138 in client.py is mispelled..

needs to be return self.get_claims(allow_**_refresh_**=False)

**Comment by chenbr** [comment]
submitting a PR

**Comment by AngellusMortis** [comment]
@chenbr Serious, you need to limit your spam. Edit existing comments, search before you make an issue or comment, etc. _EVERYTIME_ you do something in this repo it sends an email to me. I was trying to not be mean about it when the comments/necroing on old issues/PRs, but I am still getting like 10+ emails a week from you.

**Comment by chenbr** [comment]
sorry i'm just trying to get a response. I'll be more mindful

**Comment by chenbr** [comment]
closed with PR https://github.com/AngellusMortis/django_microsoft_auth/pull/412
