### ISSUE TITLE
Typo in arguments to jwt.decode

### ISSUE THREAD

**Issue by georgethomasuk** [AngellusMortis/django_microsoft_auth#431]
We have been seeing the following error crop up when using this package:

```
could verify id_token sig: It is required that you pass in a value for the "algorithms" argument when calling decode().
```

It appears that there is a typo in the argument to `jwt.decode` on line 154 of `client.py`.

I have prepped a PR to fix the issue, which I will link in a minute.

**Comment by ricardoedo** [comment]
Seeing the same issue

**Comment by emb-karan** [comment]
Please go through this fix, if anyone also getting this error
[fix](https://github.com/AngellusMortis/django_microsoft_auth/issues/439#issuecomment-757384760)

**Comment by rosscreighton** [comment]
@AngellusMortis thanks for the fix! Is there a release coming soon so we can install via PyPi?
