### ISSUE TITLE
Step 10 in the usage docs

### ISSUE THREAD

**Issue by Perzan** [AngellusMortis/django_microsoft_auth#432]
I have been trying to set up this app, but I am a stuck on [step 10 in the usage documentation](https://django-microsoft-auth.readthedocs.io/en/latest/usage.html):
```
8. Start site and go to /admin and logout if you are logged in.
9. Login as Microsoft/Office 365/Xbox Live user. It will fail. This will automatically create your new user.
10. Login as a Password user with access to change user accounts.
11. Go to Admin -> Users and edit your Microsoft user to have any permissions you want as you normally.
```

Am I supposed to create this user using `py .\manage.py createsuperuser`? I created a user with that program (Only username and password, no email), but the `/admin` page says the following when I attempt to log in with these credentials:
```
Please enter the correct username and password for a staff account. Note that both fields may be case-sensitive. 
```
I triple checked that my caps-lock key was not the problem, and I changed the HTML so I can see the password I was putting in.

Am I missing something? Am I supposed to be using a different page for what I am doing for step 10?

Thank you in advance.

**Comment by AngellusMortis** [comment]
Not an issue. Question about usage.
