### ISSUE TITLE
Install requires dependencies are not version limited

### ISSUE THREAD

**Issue by kangasta** [AngellusMortis/django_microsoft_auth#433]
The dependencies installed with this package on `pip install django-microsoft-auth` are not version locked, see [setup.py](https://github.com/AngellusMortis/django_microsoft_auth/blob/master/setup.py) and [requirements.in](https://github.com/AngellusMortis/django_microsoft_auth/blob/master/reqs/requirements.in). On the other hand, the compiled dependency list in [requirements.txt](https://github.com/AngellusMortis/django_microsoft_auth/blob/master/requirements.txt) has locked dependency versions.

This caused problems, and revealed a bug, when pyjwt package released a new major version [v2.0.0](https://github.com/jpadilla/pyjwt/releases/tag/2.0.0): #429 and #431. These unspecified version might cause problems also in future.

**Comment by AngellusMortis** [comment]
Install requires should not be version locked. `django-microsoft-auth` is a library. Having more restrictive library dependencies can cascade into larger project installations and prevent users from installing the library. 

I put some more details in the PR you made, but I would rather leave the requirements as open as possible unless there is a known incompatibility and then just exclude those versions until a fix can be made.

**Comment by kangasta** [comment]
Version locked was probably wrong term for this situation. What I meant was an upper version limit for the semantically versioned dependencies, as you mentioned in the PR.

Speaking of versions, Python 3.5 and Django 2.1 have reached end-of-life. Not sure if this would affect anything else than the test matrix and supported versions in the README. In addition, the travis-ci.org service will be shutting down in near future. Do you have plans to migrate to other CI service, such as GitHub Actions?

**Comment by AngellusMortis** [comment]
Github Actions would definitely be my preferred choice. I have already used it with a few other projects and it works really well. I will go ahead and make another issue for migrating to actions.
