### ISSUE TITLE
Django Microsoft Auth is not working on IE

### ISSUE THREAD

**Issue by ebentz73** [AngellusMortis/django_microsoft_auth#435]
* Django Microsoft Authentication Backend version: Latest Version
* Django version: 3.0
* Python version: 3.8
* Operating System: Windows
* Browser and version: IE 11
* Browser extensions/plugins you have installed: None

### Description

I tried to run the diango-microsoft-auth on windows and opened with IE11 but it shows an error.
![image_2021_01_05T13_24_10_929Z](https://user-images.githubusercontent.com/57481246/103651385-834f4680-4f2f-11eb-87ec-7f9ccb3728c0.png)

### Steps to Reproduce

Installed `django-microsoft-auth` and run on Internet Explorer.

**Comment by AngellusMortis** [comment]
Internet Explorer is not supported. If you need to support Internet Explorer, you must make your own login template and login code. 

IE needs to go away, I have  no intention having any support for it. All other Chromium-based or Firefox browsers are supported, including modern versions of Edge (which are Chromium-based).
