### ISSUE TITLE
could verify id_token sig: It is required that you pass in a value for the "algorithms" argument when calling decode().

### ISSUE THREAD

**Issue by pydevink** [AngellusMortis/django_microsoft_auth#444]
I am using Django 3.1.5 version and I configured everything exactly the same as in the Documentation. 

When I try to login using AD account, I'm getting the error : could verify id_token sig: It is required that you pass in a value for the "algorithms" argument when calling decode().

I have no idea what this means in terms of configuration - do I need to add something or?

**Comment by serl** [comment]
Hello,
Same here!
I configured `MICROSOFT_AUTH_CLIENT_ID`, `MICROSOFT_AUTH_CLIENT_SECRET` and `MICROSOFT_AUTH_TENANT_ID`. I'm trying to connect to localhost:8000/admin.

**Comment by serl** [comment]
Digging a little, it looks like it has already been solved in #430.

**Comment by pydevink** [comment]
But why do we have this error than? :)

**Comment by pydevink** [comment]
I'm using latest stable version

**Comment by serl** [comment]
Yes, sorry I didn't manage to end the sentence 😆 
That change hadn't yet been published to pip, so that's why...

**Comment by ihelmer07** [comment]
Any ETA on when #430 will be published to pip @AngellusMortis

**Comment by aydtmiri** [comment]
@ihelmer07 were you able to continue without the correction? I'm facing the same problem

**Comment by ihelmer07** [comment]
@aydtmiri - I had to update my dockerfile to clone the repo and install manually with python setup.py install.

**Comment by serl** [comment]
You could still use pip:

```bash
pip install git+https://github.com/AngellusMortis/django_microsoft_auth.git
```
