### ISSUE TITLE
Call Microsoft Authentication in a Custom Login Form

### ISSUE THREAD

**Issue by szpm102** [AngellusMortis/django_microsoft_auth#446]
Apologies am New to this feature however really would like to integrate this to my custom login form. 

Did not find any documentation how this can be done and really would like some feedback on this. So in my login there will be a button then when pressed it will redirect to Microsoft authentication site and when completed it will redirect to the homepage. 

Can you kindly guide me how it can be done?

Thanks

**Comment by nowakowsky** [comment]
Take a look on [tests](https://github.com/AngellusMortis/django_microsoft_auth/tree/master/tests/site/templates/registration), that should help
