### ISSUE TITLE
How can I prevent a Django user from being created by django_microsoft_auth backend?

### ISSUE THREAD

**Issue by SolitonMan** [AngellusMortis/django_microsoft_auth#452]
Hello,

I've been working on integrating my Django application with Azure sign in and have managed to get django_microsoft_auth to work.  Thank you!  However, in our testing we've seen that if a Microsoft authenticated non-user attempts to log in to our system they'll have User record created with their Microsoft data.  This is undesirable for our use case, but there doesn't seem to be a way to disable this behavior via settings.  Am I missing something?  If not, then I'm ok with using a fork of the code to write my own solution, but if there's a means of overriding this without going to that length it would be really useful.

**Comment by AngellusMortis** [comment]
https://github.com/AngellusMortis/django_microsoft_auth/blob/master/microsoft_auth/conf.py#L90

**Comment by SolitonMan** [comment]
I did look at that configuration setting but it wasn't achieving the desired effect.  When set to False the result is that existing users within my application's User table fail to authenticate because they don't have an entry in the microsoft_auth_microsoftaccount table.  I'd like the records in microsoft_auth_microsoftaccount to be created when an authenticated user logs in to my application, but I don't want to have User records created when a non-user who is authenticated accesses the application.
