### ISSUE TITLE
Publish master to Pip

### ISSUE THREAD

**Issue by BrutalCSkakan** [AngellusMortis/django_microsoft_auth#455]
Hello!
Is there a possibility for you owners to publish the latest master version to pip? 
The current version contains the algorithms bug where you're unable to login through the django admin portal.

**Comment by BrutalCSkakan** [comment]
Hello. Any updates? The current state of the project is broken unless the latest commit gets published to pip.

**Comment by p14z** [comment]
@BrutalCSkakan I currently have the master configured in my requirements as:

`django-microsoft-auth @ https://github.com/AngellusMortis/django_microsoft_auth/archive/master.zip`

Does the work while we wait.
