### ISSUE TITLE
Send oauth session between 2 Django applications (front and back)

### ISSUE THREAD

**Issue by srPuebla** [AngellusMortis/django_microsoft_auth#457]
Hi,

I have 2 applications, Front and Back. Front is using django_microsoft_auth to login and it is woking successfully. What we want, is recover the oauth session and send to the other backends. How can i do it?

Maybe i have to use the oauth lib, but i am lost.

Thanks!

**Comment by AngellusMortis** [comment]
Generic Django question. I cannot provide support for your application.
