### ISSUE TITLE
Login into admin does not close the microsoft window and does not reload the page.

### ISSUE THREAD

**Issue by Wissperwind** [AngellusMortis/django_microsoft_auth#484]
Hi,

I just set up microsoft login. I try to login into django admin. The user was created by the plugin and I already gave him staff and admin permission by using a superuser.
But the moment the microsoft login is completed, the window shows:

```
This window should automatically close. If it does not, it should be save to close after a few seconds.
{"microsoft_auth": {}}
```
But:
- The window does not close.
- If I close the window manually the login page does nothing. It does not automatically refresh.

If close manually and afterwards refresh manually the user is logged in. But that can't be the way a user should log in.

**Comment by abbas-mohd56** [comment]
I've been using this package for a while and started having this issue when I tried upgrading Django from 3.2 to 4.0. Since my project is already dependent on this package, I can't upgrade django until this bug is fixed .

**Comment by Wissperwind** [comment]
ok, so this is an django issue or an issue of this project?

**Comment by Casey-Kiewit** [comment]
I did some digging into this. [Django 4.0 added a security feature that breaks how this page was working.](https://docs.djangoproject.com/en/4.1/topics/security/#cross-origin-opener-policy) This change causes [these two lines to error](https://github.com/AngellusMortis/django_microsoft_auth/blob/master/microsoft_auth/templates/microsoft/auth_callback.html#L11-L12) since `window.opener` is null.

**Comment by Wissperwind** [comment]
OK, and now?

**Comment by sumitsandhir** [comment]
H Guys, I have same issue as well. Is anyone working on it as i am using Django 4.1.3. Any suggestions?

**Comment by bartTC** [comment]
The solution in in the documentation link above.  Set

```
# settings.py
SECURE_CROSS_ORIGIN_OPENER_POLICY = "none"```

https://docs.djangoproject.com/en/4.1/ref/middleware/#cross-origin-opener-policy
https://docs.djangoproject.com/en/4.1/ref/settings/#std-setting-SECURE_CROSS_ORIGIN_OPENER_POLICY

**Comment by Wissperwind** [comment]
Thank you. That solved my problem!!!
