### ISSUE TITLE
Pip install - No module named 'pip.req'

### ISSUE THREAD

**Issue by Shigumitsu** [AngellusMortis/django_microsoft_auth#63]
* Django Microsoft Authentication Backend version: 1.0.6
* Python version: 3.6.5
* Operating System: Archlinux

### Description

I would like to install your package with pip (like in your README.md), but the setup script cannot find the package pip.req.

### What I Did

```
shigumitsu@shiguarch $> pip install django_microsoft_auth

Collecting django_microsoft_auth
  Using cached https://files.pythonhosted.org/packages/b2/b2/ad16fb5d39df00f476999e7977cfb9546d2dff1eecbb8fe1ad8e6225079f/django_microsoft_auth-1.0.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fz2vh467/django-microsoft-auth/setup.py", line 8, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-fz2vh467/django-microsoft-auth/
```

**Comment by Shigumitsu** [comment]
Fixed !

**Comment by colegatron** [comment]
How did you fix it? I am in the same situation with python 3.6.6

**Comment by Shigumitsu** [comment]
> 
> 
> How did you fix it? I am in the same situation with python 3.6.6

A pull request was made, but has not been validated :/
Anyway, look this : [Link to the pull request](https://github.com/AngellusMortis/django_microsoft_auth/pull/64/commits/24e4b5e7775b563d231cd2706ab282ab5fc48100)

**Comment by AngellusMortis** [comment]
@colegatron Upgrade to 1.1.0 or downgrade pip to 9.0.3.
