### ISSUE TITLE
Can't login via admin - AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application

### ISSUE THREAD

**Issue by radzhome** [AngellusMortis/django_microsoft_auth#83]
After following all instructions, I am still getting an error from the login page

```
Sign in
Sorry, but we’re having trouble signing you in.

AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: '<my app id>'.
```

![screen shot 2018-07-26 at 10 26 56 am](https://user-images.githubusercontent.com/2678007/43268389-83eaf6b6-90be-11e8-950c-c413f13ed39e.png)
![screen shot 2018-07-26 at 10 27 04 am](https://user-images.githubusercontent.com/2678007/43268390-83fe5e9a-90be-11e8-9797-b54451a8888e.png)

redirect urls:

![screen shot 2018-07-26 at 10 27 45 am](https://user-images.githubusercontent.com/2678007/43268415-95981132-90be-11e8-9a0f-fffee4146799.png)

Not sure what is missing, maybe MS changed something?

**Comment by radzhome** [comment]
I'm on django 2.0.7, python 3.7 if it helps

**Comment by AngellusMortis** [comment]
From the setup instructions:

> Make sure you update the domain of SITE_ID

> Add a Web Platform with Allow Implicit Flow and a valid Redirect URL (this will probably be https://<your-domain>/microsoft/auth-callback/), it **must be HTTPS**

You absolutely 100% have to set up and configure the sites framework. `microsoft_auth` uses the Sites framework to generate an absolute URL to pass to Microsoft for the callback URL. This callback URL **must be HTTPS**. Microsoft will not do call backs to HTTP URLs. 

Use [Let's Encrypt/Certbot](https://certbot.eff.org) or something and [nginx to set up a reverse proxy](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/) to your local development app if you want to test the Microsoft authentication.
